<?php

namespace AppBundle\Repository;

/**
 * BuildingInsideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingInsideRepository extends \Doctrine\ORM\EntityRepository
{
}
