<?php

namespace AppBundle\Repository;

/**
 * InventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventionRepository extends \Doctrine\ORM\EntityRepository
{
}
