<?php

namespace AppBundle\Repository;

/**
 * MiniTchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiniTchatRepository extends \Doctrine\ORM\EntityRepository
{
}
