<?php

namespace AppBundle\Repository;

/**
 * OrderCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCostRepository extends \Doctrine\ORM\EntityRepository
{
}
