<?php

namespace AppBundle\Repository;

/**
 * OrderrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderrRepository extends \Doctrine\ORM\EntityRepository
{
}
