<?php

namespace AppBundle\Repository;

/**
 * OrderInfluenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderInfluenceRepository extends \Doctrine\ORM\EntityRepository
{
}
