<?php

namespace AppBundle\Repository;

/**
 * PersonageInventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonageInventionRepository extends \Doctrine\ORM\EntityRepository
{
}
