<?php

namespace AppBundle\Repository;

/**
 * PersonageStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonageStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
