<?php

namespace AppBundle\Repository;

/**
 * RapportValidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportValidRepository extends \Doctrine\ORM\EntityRepository
{
}
