<?php

namespace AppBundle\Repository;

/**
 * RapportErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
